export type SubmissionStatus = 
  | "PENDING" 
  | "ENQUEUING" 
  | "QUEUED" 
  | "RUNNING" 
  | "PROCESSING" 
  | "COMPLETED" 
  | "WRONG_ANSWER"
  | "SYSTEM_ERROR" 
  | "CANCELLED"
  | "COMPILE_ERROR"
  | "RUNTIME_ERROR"
  | "TIME_LIMIT_EXCEEDED"
  | "MEMORY_LIMIT_EXCEEDED";
